%% Fig 7 eNeuro manuscript - Correlations of two intrinsic conductances
%% across 6 animals

%% TODO: 
% - requires pace_bestsyns_search_allconds, common scripts, and data

% common include
common

% join function
join_it = @(a_ranked_db) ...
          joinOriginal(a_ranked_db, ':', ...
                       struct('keepScores', 1, 'origCols', '/ItemIndex/', ...
                              'rankedCols', 'Max'));

% make a plot function (copy paste into Matlab)
plot_scat = @(all_db, good_db, col1, col1_name, col2, col2_name, a_title) ...
    plot_superpose({...
      set(plotScatter(all_db, col1, col2, a_title, '', ...
                      struct('LineStyle', '.', 'quiet', 1, ...
                             'plotProps', ...
                             struct('MarkerEdgeColor', [0.7725    0.6196    0.0941]), ...
                             'noLegends', 1, ...
                             'axisLimits', [0 50 0 50], ...
                             'XTick', [0 25 50], ...
                             'XTickLabel', {{'0', '50%', '100%'}}, ...
                             'YTick', [0 25 50], ...
                             'YTickLabel', {{'0', '50%', '100%'}}, ...
                             'fixedSize', [2.5 2])), ...
          'axis_labels', {col1_name, col2_name}), ...
      plotScatter(good_db, col1, col2, a_title, '', ...
                  struct('LineStyle', '.', 'quiet', 1, ...
                         'plotProps', ...
                         struct('MarkerEdgeColor', [0.4078    0.0549    0.5255]), ...
                         'Regress', ...
                         struct('plotProps', ...
                                struct('Color', 'k', 'LineWidth', 2, 'LineStyle', '-'))))}, '', {}, ...
                          struct('noCombine', 1));


% load all animal model data
scat_plots = {};
j_bestsyn_db = {};
num_runs = 5; % 5 for all
for input_num = [1 2 3 4 5 6] % 
  if input_num == 4
    start_index = 29;
  else
    start_index = 17;
  end
  j_bestsyn_db{input_num} = {params_tests_db, params_tests_db};
  for run_num = 1:num_runs
    [a_bundle, a_ranked_db] = ...
        pace_bestsyns_search_allconds(input_num,47,start_index+run_num,NaN,NaN,NaN);
    j_db = join_it(a_ranked_db);
    j_bestsyn_db{input_num}{1} = [ j_bestsyn_db{input_num}{1}; j_db ];
    j_bestsyn_db{input_num}{2} = [ j_bestsyn_db{input_num}{2}; ...
                        j_db(j_db(:, 'Max') < 1, :) ];
  end
  disp([ 'Good model ratio=' ...
         num2str(dbsize(j_bestsyn_db{input_num}{2}, 1) / ...
                 dbsize(j_bestsyn_db{input_num}{1}, 1)) ])
  scat_plots{input_num} = ...
      plot_scat(j_bestsyn_db{input_num}{1}, j_bestsyn_db{input_num}{2}, ...
                'neurite_P', 'neurite P', ...
                'neurite_K2', 'neurite K_2', ...
                [ strrep(input_names{input_num}, '_', '/') ] );
end
